spring.application.name=agrihub

spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:34400/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SMUAsloWKOEGcXasTuxLyqKyMmgLZOmq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}